### PR TITLE
Feat: Add swipe support, option to disable scrolling and loop next/previous

### PR DESCRIPTION
**Pull request by kevinsimard**
Feature request: Support swipe #63

Here are some new features I added to my fork:

- Add ability to swipe left/right on desktop and mobile
- Add option to disable scrolling when modal is visible
- Allow user to navigate from beginning to end and vice versa
- Rename the on-prev-click/on-next-click events to on-prev/on-next

Remaining work:
- Update changelog with new features/properties
- Bump minor version since the events were renamed
- Update docs and other language READMEs

Any feedback?

### CODE REVIEW

**Comment by kevinsimard** [comment]
@XiongAmao

**Comment by XiongAmao** [comment]
Thank you for your PR.

I was editing PR on my local editor and accidentally merged it. 😭

I've made some changes: 

1. feat: keep previous on-*-click events
2. feat: keep the last body.style.overflowY
3. fix: dragging distance incorrect

I'll do the rest of the docs updates later, and then release the new version.

**Comment by squaretrax** [comment]
@XiongAmao Great, thank you 👍  Glad I could help!

**Comment by kevinsimard** [comment]
@XiongAmao Great, thank you, glad I could help! 👍

**Comment by izidorit** [comment]
Hi,
Very plane and clear tool, thank you for it.
Is there any chance to add swipe support for Vue2 too? If I'm correct it only works with Vue3 :(
The only thing I'm missing from it.

**Pull request merged**
